### ISSUE TITLE
Steps fail to install all node dependencies

### ISSUE THREAD

**Issue by Saurbaum** [mikeghen/litecoin-solo-mining-tutorial#1]
multihashing.target.mk:138: recipe for target 'Release/obj.target/multihashing/multihashing.o' failed
make: *** [Release/obj.target/multihashing/multihashing.o] Error 1
make: Leaving directory '/opt/stratum-server/node_modules/multi-hashing/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.13.0-1009-azure
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /opt/stratum-server/node_modules/multi-hashing
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:multi-hashing@0.0.9 multi-hashing@0.0.9 install: `node-gyp rebuild`
npm WARN install:multi-hashing@0.0.9 Exit status 1

Username is ubuntu so all steps should exactly match the steps from the readme.  All commands run as super user.

**Comment by mikeghen** [comment]
`node -v v4.2.6`
I have see this error with other versions of Node. Revisit Step 3, make sure you run:
```
nvm install v0.10.25
```
Let me know if you get it working @Saurbaum

**Comment by mikeghen** [comment]
@Saurbaum, email me if this is still an issue for you
